
module.exports = function(grunt) {
    grunt.registerTask("grp-test-svr-build1", ["s1"]);
    grunt.registerTask("grp-test-svr-build2", ["s2"]);
    grunt.registerTask("grp-test-svr-build3", ["s3"]);
    grunt.registerTask("grp-test-svr-build4", ["s4"]);
    grunt.registerTask("grp-test-svr-build5", ["s5"]);
    grunt.registerTask("grp-test-svr-build6", ["s6"]);
    grunt.registerTask("grp-test-svr-build7", ["s7"]);
};
